[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_speed = 115200
build_flags =
    -DFIRMWARE_VERSION=\"smart-plant-bed-esp32dev-m14-0.1-wifi-setup\"
build_src_filter =
    +<*>
    -<DisplayManager.cpp>
    -<ValveController.cpp>

lib_deps =
    bblanchon/ArduinoJson
    adafruit/DHT sensor library
    adafruit/RTClib
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
